### ISSUE TITLE
add calculators?

### ISSUE THREAD

**Issue by rlanzafame** [TUDelft-CITG/learn-probability#12]
should we add an interactive python block somewhere?

**Comment by ahmedfarhatx22** [comment]
Maybe at: 
1- Section 01: Total Probability Theorem, chapter 3. "Concrete Compressive strength" ; packages used:
       *from jupyterquiz import display_quiz

2- Section 02: 2_1_Bernoulli_dist,  chapter 3. "International master's student population" (after first question); packages used:
    * from jupyterquiz import display_quiz
    
3- Section 02: 2_2_Binomial_dist,  chapter 3. "Structural deficient bridges"; packages used:
    * from jupyterquiz import display_quiz 
    * from scipy.special import comb

4- Section 02: 2_3_Geometric_dist,  chapter 3. "Heavy Vehicles"; packages used:
    * from jupyterquiz import display_quiz 
 
5- Section 02: 2_3_Geometric_dist,  chapter 3. "Hurricanes"; packages used:
    * from jupyterquiz import display_quiz 
    * import numpy as np

6- Section 03: 3_3_Normal_dist,  chapter 3. "Reinforcement bar tensile strength"; packages used:
    * from jupyterquiz import display_quiz 
    * from IPython.display import HTML (for video, maybe we change this if we want to use video that is not on youtube?)
    * import warnings (for video)
    * warnings.filterwarnings('ignore') ---> (for video)
    * from scipy.stats import norm
