### ISSUE TITLE
find where a jupyter lite cell may be useful

### ISSUE THREAD

**Issue by rlanzafame** [TUDelft-CITG/learn-probability#21]
we will set up one "sandbox" page, then add links to the sandbox page from the pages where it might be useful.

**Comment by ahmedfarhatx22** [comment]
Assuming that we use the cell blocks, here would be nice places but not needed 100% as questions are fairly easy: 
Maybe at:
1- Section 01: Total Probability Theorem, chapter 3. "Concrete Compressive strength" ; packages used:
*from jupyterquiz import display_quiz

2- Section 02: 2_1_Bernoulli_dist, chapter 3. "International master's student population" (after first question); packages used:
* from jupyterquiz import display_quiz

3- Section 02: 2_2_Binomial_dist, chapter 3. "Structural deficient bridges"; packages used:
* from jupyterquiz import display_quiz
* from scipy.special import comb

4- Section 02: 2_3_Geometric_dist, chapter 3. "Heavy Vehicles"; packages used:
* from jupyterquiz import display_quiz

5- Section 02: 2_3_Geometric_dist, chapter 3. "Hurricanes"; packages used:
* from jupyterquiz import display_quiz
* import numpy as np

6- Section 03: 3_3_Normal_dist, chapter 3. "Reinforcement bar tensile strength"; packages used:
* from jupyterquiz import display_quiz
* from IPython.display import HTML (for video, maybe we change this if we want to use video that is not on youtube?)
* import warnings (for video)
* warnings.filterwarnings('ignore') ---> (for video)
* from scipy.stats import norm
